-- liquibase formatted sql
-- changeset paglebov_1@edu.hse.ru:1 -comment:Comment for user
create table if not exists sessions
(
      id       int          generated by default as identity primary key
    , user_id  int          not null
    , token    varchar(255) not null
    , expires  timestamp    not null
    , foreign key (user_id) references users(id)
);
-- rollback delete sessions;